### PR TITLE
add bufferutil and utf-8-validate to node dependencies

### PR DESCRIPTION
**Pull request by xCuri0**

### CODE REVIEW

**Comment by lfern** [comment]
merged!

**Comment by xCuri0** [comment]
@lfern do you have a list of requirements we need before websocket-multiple can be merged into ccxt/master ?

**Comment by xCuri0** [comment]
afaik its the php build since it fails with
```
PHP Warning:  Uncaught ErrorException: require(/media/storage/Documents/src/ccxt/php/../vendor/autoload.php): failed to open stream: No such file or directory in /media/storage/Documents/src/ccxt/php/Exchange.php on line 36 in /media/storage/Documents/src/ccxt/php/test/syntax.php:12
Stack trace:
#0 /media/storage/Documents/src/ccxt/php/Exchange.php(36): on_error(2, 'require(/media/...', '/media/storage/...', 36, Array)
#1 /media/storage/Documents/src/ccxt/php/Exchange.php(36): require()
#2 /media/storage/Documents/src/ccxt/ccxt.php(39): require_once('/media/storage/...')
#3 [internal function]: ccxt\{closure}('Exchange')
#4 /media/storage/Documents/src/ccxt/php/test/syntax.php(19): spl_autoload_call('ccxt\\Exchange')
#5 {main}
  thrown in /media/storage/Documents/src/ccxt/php/test/syntax.php on line 12
PHP Fatal error:  main(): Failed opening required '/media/storage/Documents/src/ccxt/php/../vendor/autoload.php' (include_path='.:') in /media/storage/Documents/src/ccxt/php/Exchange.php on line 36
```

**Comment by lfern** [comment]
> @lfern do you have a list of requirements we need before websocket-multiple can be merged into ccxt/master ?

@xCuri0 I don't really know which requirements would be needed. Only ccxt mantainers could give a clue about this. But in this request

https://github.com/ccxt/ccxt/pull/4335 

I can't find a list of requirements to achive that. I think it could be a dependency problem, because we need websockets,pako... dependencies and they are trying to make ccxt with zero external dependencies. But I don't really know what is the problem with this merge. Some people are asking about when would be ready, and offer their help for merging it, but i think they have not received any response about it.

**Pull request merged**
