### PR TITLE
Fix transpiler and make cobinhood websocket ping

### PR DESCRIPTION
**Pull request by xCuri0**

### CODE REVIEW

**Comment by xCuri0** [comment]
@lfern do you know any wae that i can reconnect if a pong isn't recieved. Because I ran a trade bot using this and after around 24 hours it stopped receiving

**Comment by lfern** [comment]
Well, I think you could close that connection id (conexid or contextid) and resubscribe all symbols again. Maybe you could send an exception in 'err' event and capture it and reinitialize the exchange.

**Comment by xCuri0** [comment]
@lfern could you implement a watchdog timer so that if it doesn't receive a pong back from the server it reconnects

**Comment by lfern** [comment]
I have tried to avoid including connect/disconnect code or invocation from to be transpiled code. I think it could be better to create some exception classes or messages that could be emited from exchange and control this connection/disconnection/reconnection events from outside. What do you think about it?

On the other hand, I don't know if ccxt mantainers could merge this branch in master. they say it is very difficult and could take some months (or maybe never) and I am affraid that if we improve too much the actual code with something like this (monitorize connections and make decisions about current status -it would be great!!).

**Comment by lfern** [comment]
@xCuri0 I am testing new methods to recover connections. Maybe you can test cobinhood. Now  when pong isn't received it emit 'err' with RequestTimeout error. When you receive this error you can invoke websocketRecoverConxid method with conxid received and exchange would try to connect subscribing to symbols that was subscribed before error. 

```python
    @exchange.on('err')
    async def websocket_error(err, conxid):  
        if isinstance(err, ccxt.NetworkError):
            exchange.websocketClose(conxid)
            print("waiting 5 seconds ...")
            await asyncio.sleep(5)
            await exchange.websocketRecoverConxid(conxid)
...
```

**Comment by xCuri0** [comment]
@lfern gives this error
```
Exception in callback EventEmitter.emit.<locals>._callback(<Task finishe...ute 'close'")>) at /usr/lib/python3.7/site-packages/pyee-5.0.0-py3.7.egg/pyee/__init__.py:163
handle: <Handle EventEmitter.emit.<locals>._callback(<Task finishe...ute 'close'")>) at /usr/lib/python3.7/site-packages/pyee-5.0.0-py3.7.egg/pyee/__init__.py:163>
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.7/site-packages/pyee-5.0.0-py3.7.egg/pyee/__init__.py", line 167, in _callback
    self.emit('error', exc)
  File "/usr/lib/python3.7/site-packages/pyee-5.0.0-py3.7.egg/pyee/__init__.py", line 178, in emit
    raise args[0]
  File "./macdbot-test.py", line 40, in websocket_error
    exchange.websocketClose(conxid)
  File "/usr/lib/python3.7/site-packages/ccxt-1.18.152-py3.7.egg/ccxt/async_support/base/exchange.py", line 714, in websocketClose
    websocket_conx_info['conx'].close()
  File "/usr/lib/python3.7/site-packages/ccxt-1.18.152-py3.7.egg/ccxt/async_support/websocket/websocket_connection.py", line 107, in close
    self.client._closeConnection(True)
  File "/usr/lib/python3.7/site-packages/autobahn-19.2.1-py3.7.egg/autobahn/asyncio/websocket.py", line 128, in _closeConnection
    self.transport.close()
AttributeError: 'NoneType' object has no attribute 'close'
```

**Comment by xCuri0** [comment]
@kroitor What are the requirements for the websocket branch to be merged into master ?

**Comment by kroitor** [comment]
@xCuri0 sorry for the long delays with my answer on this, I will post our roadmap and all the info will be there.

**Pull request merged**
