### PR TITLE
Binance trade and aggTrade orderbook event

### PR DESCRIPTION
**Pull request by ghost**
Binance has two different trade stream: raw trades and aggregated trades.

I would also like to propose an additional method for subscribing to websockets.
Since Binance uses the ws-s configuration we have to get the full orderbook from the REST API every time a symbol is added. This can result in a ddos protection response from streaming server when subscribing to many symbols at once.
I came up with a possible solution but only coded in python, I might find the time to also make it in javascript. Anyway tell me what you think.
A simple way around this would be to add two general public functions, one private function and a member object `pending_subs`:
```
websocket_add_subscriptions(self, event, symbol_list, params={})
# Creates entry self._pending_subs[event] = subs_list
# subs_list is an array of subs objects of the form:
# {
#     'event': event,
#     'symbol': symbol,
#     'params': params,
# }

deploy_subscriptions(self, event):
# Iterates all subs in self._pending_subs[event]
# for each sub calls self._websocket_ensure_conx_active(event, symbol, subscribe=True, connect=False)
# Then call self._websocket_deploy_subscriptions(conxid, subs_list)

_websocket_deploy_subscriptions(self, conxid, subs_list)
# For non ws-s type API this will simply subscribe to all symbols
# self.websocket_subscribe(sub['event'], sub['symbol'], sub['params'])
# But a ws-s type API can overide this method.
# All subs in subs_list are iterated and the wss URL is build.
# Then we only need a single call to self.websocket_connect(conxid)

_websocket_ensure_conx_active(self, event, symbol, subscribe, connect=True):
# With the new optional argument we can omit a call to websocket_connect() while still building the context.
# Original behavior of this method is unchanged.
    ...
    if connect:
        await self.websocket_connect()

```

### CODE REVIEW

**Comment by lfern** [comment]
Thanks @yevsev this is merged on websocket/multiple branch. About binance subscription, I think we could implement as you suggests, but I would modify _websocket_ensure_conx_active to receive a event/symbol list. Then we could change websocket:subscribe to receive and event list or create a new function websocket_subscribe_all with this event list parameter.

**Comment by ghost** [comment]
Hi @lfern, thanks for your reply. I have considered modifying `_websocket_ensure_conx_active()` when I started to implement these methods in python. However, I ended up calling almost the entire function for each pending subscription. I didn't think that calling `_websocket_ensure_conx_active()` a large number of times would cause a problem other than repeated calls to `websocket_connect().` So I added an optional argument: 
`_websocket_ensure_conx_active(event=event, symbol=symbol, subscribe=True, connect=True)`
so that `websocket_connect()` is only called `if connect == True`. When `connect == False` the URL is build up and we can call `websocket_connect()` after all subscriptions have been added. It doesn't influence the rest of the code.

In javascript it could be added to `subscriptionParams` and if not present it defaults to `connect = true`.
`_websocketEnsureConxActive (event, symbol, subscribe, subscriptionParams = {})`.
Maybe modifying the function to take a list of `(event, symbol)` tuples would be easier to implement in javascript. 

I'd like to hear what you think is the best solution.

**Comment by lfern** [comment]
Hi @yevsev. I think if we implement this way it would only works on binance or any other exchange that only has unique websocket endpoint. If binance would have one endpoint for orderbooks and other for trades, then you have to take this into account to invoke _websocket_ensure_conx_active with connect parameter True for the last subscription on each endpoint. I think it could be better to add pending connections, as you suggest, in _websocket_ensure_conx_active passing a list of subscriptions or unsubscriptions:
```python
connections = {}
for event_symbol in subscriptions:
  ret = self._websocketGetConxid4Event(event, symbol)
  conxid = ret['conxid']
  conxtpl = ret['conxtpl']
  merge_connection(connections, conxid, conxtpl)
# here you will have a list of connections for each conxi d(endpoint)
# and only have to do a loop with the rest of _websocket_ensure_conx_active body.
```
(Maybe this merge operations must to be done in _websocketGetConxid4Event method.)

**Comment by ghost** [comment]
I'm not sure if I understand correctly. In my websocket testing code I never invoke `_websocket_ensure_conx_active(self, event, symbol, subscribe, connect=True)` for a ws-s exchange like Binance. Part of my code is below, let met know what you think. Maybe I'm just completely missing the point that you are making :)
```
async def websocket_deploy_subscriptions(self, event):
	'''
	Deploy all pending subscriptions for a specific event.
	'''
	if not isinstance(event, str):
		raise ValueError(self.id + ' expected type \"str\" for parameter \"event\" but got ' + type(event))
	if not self._websocketValidEvent(event):
		raise ExchangeError('Not valid event ' + event + ' for exchange ' + self.id)

	self.wslogger.debug(self.id + ' deploying event ' + event)
	subs_list = self.pending_subs[event]
	conxid = 'firstrun'
	for sub in subs_list:
		symbol = sub['symbol']
		conxid_new = await self._websocket_ensure_conx_active(event=event, symbol=symbol, subscribe=True, connect=False)
		self._contextSetSubscribing(conxid_new, event, symbol, True)
		if isinstance(conxid, str):
			if conxid == 'firstrun':
				conxid = conxid_new
				continue
		if conxid_new != conxid:
			raise ValueError(self.id + ' Mismatching conxid in list of subscriptions: ', json.dumps(subs_list,indent=2))
		conxid = conxid_new
	try:
		await self._websocket_deploy_subscriptions(conxid, subs_list)
	except Exception:
		self.wslogger.error(self.id + ' Error in call to _websocket_deploy_subscriptions(). ', exc_info=True)
	del self.pending_subs[event]

async def _websocket_deploy_subscriptions(self, conxid, subs_list):
	'''
	Override this method in exchange specific class. Exchanges of type ws-s greatly benefit from this function.
	For example, in binance, we would only have to call make a "await self.websocket_connect()" in this function.
	:param conxid str key for getting websocket object
	:param subs_list dict with fields {'event', 'symbol', 'params'}
	'''
	for sub in subs_list:
		await self.websocket_subscribe(event=sub['event'], symbol=sub['symbol'], params=sub['params'])
		await asyncio.sleep(0.021)
```
In binance.py:
```
async def _websocket_deploy_subscriptions(self, conxid, subs_list):
	'''
	:param conxid str key for getting websocket object
	:param subs_list dict with fields {'event', 'symbol', 'params'}
	'''
	self.wslogger.debug('Subscribing to ' + str(len(subs_list)) + ' markets.')
	# We only have to connect now.
	for sub in subs_list:
		event = sub['event']
		symbol = sub['symbol']
		params = sub['params']
		self.wslogger.debug('Subscribing to ' + event + ' - ' + symbol)
		data = self._contextGetSymbolData(conxid, event, symbol)
		data['params']['limit'] = self.safe_integer(params, 'limit', None)
		self._contextSetSymbolData(conxid, event, symbol, data)
		self._websocket_subscribe(conxid, event, symbol, nonce='ignore', params={})
	await self.websocket_connect(conxid=conxid)
```

Taking Binance as an example and we want to subscribe to websocket orderbook and trades at the same time. We get two connections to Binance with two different URLs:
orderbook: `wss://stream.binance.com:9443/stream?streams=btcusdt@depth`
trades: `wss://stream.binance.com:9443/stream?streams=btcusdt@trade`

Another possibility is to connect to orderbook stream and trades stream in the same URL which is arguably better:
orderbook and trades: `wss://stream.binance.com:9443/stream?streams=btcusdt@depth/btcusdt@trade`
This can easily be implemented by changing the method
`deploy_subscriptions(self, event)` to `deploy_subscriptions(self)`
so that we deploy all pending subscriptions for all events.

**Comment by lfern** [comment]
> 
> ```python
> if conxid_new != conxid:
>   raise ValueError(self.id + ' Mismatching conxid in list of subscriptions: ', json.dumps(subs_list,indent=2))
> ```
This means that you can't subscribe events/symbols that use different conxids (or differents endpoints). If you invoke websocket_deploy_subscriptions outside ccxt you must to know about binance conxids, mustn't you?

**Comment by lfern** [comment]
@yevsev , maybe I must see your code complete. I think I don't understand how do you are implementing this. I try to access your branch and check it out.

**Comment by ghost** [comment]
@lfern I added the new methods to the python baseclass here:
https://github.com/yevsev/ccxt/commit/4e2638645f99dc84cd8a580133b316be107787ce

Code for subscribing to orderbook streams is given below.

```
for exchange in self._exchange_list:
	symbol_list = self.get_market_ids_by_exchange(exchange.id)
	logger.debug(exchange.id + ': subscribing to ' + str(len(symbol_list)) + ' orderbook feeds.')
	exchange.add_subscriptions(event='ob', symbol_list=symbol_list, params={'limit': limit, 'depth': limit})
# Call all async methods at the same time
await asyncio.wait([exchange.deploy_subscriptions('ob') for exchange in self._exchange_list])
```

This code makes sure that all pending subscriptions that are deployed have the same conxid so yes, you are right. I made the assumption that subscriptions with the same event will have the same conxid.
```
conxid_new = await self._websocket_ensure_conx_active(event=event, symbol=symbol, subscribe=True, connect=False)

...

if conxid_new != conxid:
  raise ValueError(self.id + ' Mismatching conxid in list of subscriptions: ', json.dumps(subs_list,indent=2))
conxid = conxid_new
```

**Comment by lfern** [comment]
Thanks @yevsev . Please, let me know if I am right:
to subscribe on binance client must invoke like this:
```python
# after exchange intialization...
exchange.websocket_add_subscriptions('ob',['ETH/BTC'], params={})
exchange.websocket_deploy_subscriptions('ob')
```
but you are assuming that all orderbook symbols would have the same endpoint (contextid). What if other ws-s exchange would have one websocket endpoint for each symbol? 

I would like that clients do not have to know how events or symbols are configures over endpoints,so they could invoke subscribe methods in the same way.

I have created a new branch (https://github.com/lfern/ccxt/tree/feature/delayed-connection) with an example that modifies binance configuration to simulate different endpoints (context-ids) to each orderbook symbol: https://github.com/lfern/ccxt/blob/feature/delayed-connection/examples/py/websocket-binance-subscribe-all.py#L54

If you execute this example (I have fixed some issues in binance..js so you must transpile before testing) like this ` python3 examples/py/websocket-binance-subscribe-all.py 1 ETH/BTC BTC/USDT ETH/USDT XRP/BTC`, it shows how subscribing/subscribing should work with different endpoints (or how I think it should work). Second run shows real binance configuration with only one endpoint.

In this brach I have modified _websocket_ensure_conx_active the way you propose, and added a websocket_subscribe_all method to subscribe any combination of event/symbols (I have only tested on orderbook, but I think it should work)

**Comment by ghost** [comment]
Hi @lfern, you are correct and the method I proposed does not work if there are different endpoints for different symbols.

Your solution seems better :)
I will test/review the delayed-connection branch this week.

cheers

**Pull request merged**
